version: '3.2'
services:
#Mysql Container
  mysql:
    image: mariadb:10.5.8
    container_name: mariadb
    hostname: mariadb
    volumes:
      - /var/lib/mariadb:/var/lib/mariadb
    env_file:
      - ./mysql.env
    restart: always  
    
  #Mediawiki Container
  mediawiki:
    image: mediawiki
    container_name : wiki_easyroll
    hostname: wiki
    ports:
      - "80:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/www/html/mediawiki/:/var/www/html/mediawiki
    restart: always
